# Generated by Django 4.1 on 2022-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='painting',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
